package core.commands.CreateCommand.enums;
//TODO add more commands
public enum CommandType {
    CREATEROUTE,
    CREATEPACKAGE,
    LISTROUTES,
    LISTPACKAGES,
    LISTTRUCKS,
    LISTFREEVEHICLES,
    FINDROUTE,
    ASSIGNROUTE,
    ADDCHECKPOINT,
    ASSIGNTRUCK,
    SAVESTATE,
    SHOWCHECKPOINTS,
    BULKASSIGN,
    COMPLETEROUTE,
    VIEWPACKAGEBYID,

}
